import type { Club, Race, UnconfirmedClub, ClubProfile } from "./types";

export const clubs: Club[] = [
  {
    slug: "orlando-runners-club",
    name: "Orlando Runners Club",
    days: ["Wed", "Sun"],
    time: "Wed 6:00 AM · Sun AM long run",
    cal: { day: "Wed", h: 6, m: 0 },
    location: "Einstein Bagels",
    area: "College Park",
    region: "Central Orlando",
    perk: "Est. 1976 · pizza & drinks after some runs",
    tags: ["all paces", "social", "free"],
  },
  {
    slug: "ten10-run-club",
    name: "Ten10 Run Club",
    days: ["Tue"],
    time: "Tuesday evening",
    cal: null,
    location: "Ten10 Brewing Co.",
    area: "Mills 50",
    region: "Central Orlando",
    instagram: "ten10brewing",
    perk: "Happy-hour beer pricing · 1–5 mi, your call",
    tags: ["all paces", "brewery", "free"],
  },
  {
    slug: "ivanhoe-park-brewing-run-club",
    name: "Ivanhoe Park Brewing Run Club",
    days: ["Wed"],
    time: "Wednesday 7:00 PM",
    cal: { day: "Wed", h: 19, m: 0 },
    location: "Ivanhoe Park Brewing",
    area: "Ivanhoe",
    region: "Central Orlando",
    instagram: "ivanhoeparkbrewing",
    perk: "Free beer after + raffle (Track Shack gear)",
    tags: ["all paces", "brewery", "free"],
  },
  {
    slug: "fleet-feet-persimmon-hollow",
    name: "Fleet Feet / Persimmon Hollow",
    days: ["Wed"],
    time: "Wednesday 6:45 PM",
    cal: { day: "Wed", h: 18, m: 45 },
    location: "227 N Eola Dr",
    area: "Thornton Park",
    region: "Central Orlando",
    perk: "Brewery discounts after · waiver on socials",
    tags: ["all paces", "social", "free"],
  },
  {
    slug: "milk-district-run-club",
    name: "Milk District Run Club",
    days: ["Thu"],
    time: "Thursday 6:30 PM",
    cal: { day: "Thu", h: 18, m: 30 },
    location: "Sideward Brewing",
    area: "Milk District",
    region: "Central Orlando",
    instagram: "milk_district_run_club",
    perk: "15% off your tab after · group 5K",
    tags: ["all paces", "brewery", "free"],
    hasProfile: true,
  },
  {
    slug: "orlando-social-run-club",
    name: "Orlando Social Run Club",
    days: ["Thu"],
    time: "Thursday 6:30 PM",
    cal: { day: "Thu", h: 18, m: 30 },
    location: "The Yard at Ivanhoe (rotates)",
    area: "Ivanhoe",
    region: "Central Orlando",
    perk: "Pizza, drinks, raffles · coach-led warm-up",
    tags: ["all levels", "social", "rotates"],
    newbie:
      "Big, welcoming crowd. Walk it or run it — first-timers blend right in, and there’s food after.",
  },
  {
    slug: "lake-eola-run-walk-club",
    name: "Lake Eola Run & Walk Club",
    days: ["Thu"],
    time: "Thursday ~6:30 PM",
    cal: { day: "Thu", h: 18, m: 30 },
    location: "Earthy Picks",
    area: "Downtown",
    region: "Central Orlando",
    instagram: "earthypicks",
    perk: "Loop of Lake Eola · healthy refreshments",
    tags: ["runners & walkers", "social", "free"],
    newbie:
      "Built for runners AND walkers around a flat, scenic lake loop. Zero pressure on pace.",
  },
  {
    slug: "fleet-feet-maitland-brewlando",
    name: "Fleet Feet Maitland × Brewlando",
    days: ["Thu"],
    time: "Thursday night",
    cal: null,
    location: "Fleet Feet Maitland",
    area: "Maitland",
    region: "North · Winter Park / Maitland",
    instagram: "fleetfeetmaitland",
    perk: "Finish at Brewlando · demo new shoes",
    tags: ["all paces", "run store", "free"],
  },
  {
    slug: "home-state-run-club",
    name: "Home State Run Club",
    days: ["Mon"],
    time: "Monday 6:45 PM (meet 6:30)",
    cal: { day: "Mon", h: 18, m: 45 },
    location: "Home State Brewing",
    area: "Hamlin",
    region: "West · Winter Garden",
    perk: "15% off after · everyone back in 45 min",
    tags: ["all paces", "brewery", "free"],
  },
  {
    slug: "park-brewing-run-club",
    name: "Park Brewing Run Club",
    days: ["Mon"],
    time: "Monday night",
    cal: null,
    location: "Park Brewing",
    area: "Lake Nona",
    region: "East · Lake Nona",
    perk: "Flat 5K · free drink at finish · a PT leads it",
    tags: ["beginner-friendly", "brewery", "free"],
    newbie:
      "A flat, easy 5K led by a physical therapist, with a free drink at the end. Gentlest start in town.",
  },
  {
    slug: "runcfl",
    name: "RunCFL",
    days: ["Mon", "Wed", "Sat"],
    time: "Mon/Wed 5:15 AM · Sat 6:00 AM",
    cal: { day: "Sat", h: 6, m: 0 },
    location: "Writer’s Block (Sat)",
    area: "Winter Garden",
    region: "West · Winter Garden",
    instagram: "runcfl",
    perk: "Early-morning crew · multiple meetups",
    tags: ["all levels", "morning", "free"],
  },
  {
    slug: "winter-garden-runners",
    name: "Winter Garden Runners",
    days: ["Tue", "Thu", "Sat"],
    time: "Early AM, multiple days",
    cal: null,
    location: "Downtown Winter Garden",
    area: "Winter Garden",
    region: "West · Winter Garden",
    instagram: "wintergardenrunners",
    perk: "West-side morning runners",
    tags: ["all levels", "morning", "free"],
  },
  {
    slug: "grit-running-orlando",
    name: "Grit Running Orlando",
    days: ["Sat"],
    time: "Saturday 7:45 AM",
    cal: { day: "Sat", h: 7, m: 45 },
    location: "Williams Family YMCA",
    area: "Orlando",
    region: "Central Orlando",
    perk: "Community-focused Saturday group",
    tags: ["all levels", "community", "free"],
  },
  {
    slug: "o-town-blazers",
    name: "O-Town Blazers",
    days: ["Sat"],
    time: "Saturday morning",
    cal: null,
    location: "Rotating trailheads",
    area: "Greater Orlando",
    region: "Trails · rotates",
    perk: "Different trail every week",
    tags: ["all paces", "trail", "free"],
  },
];

export const unconfirmedClubs: UnconfirmedClub[] = [
  {
    name: "Running for Brews Orlando",
    time: "Weekly · day not confirmed",
    location: "Rotating bar/brewery",
    area: "Orlando",
    perk: "Post-run brews + weekly raffles",
    tags: ["all levels", "social", "verify"],
  },
  {
    name: "Tactical Brewing Run Club",
    time: "Weekly · day not confirmed",
    location: "Tactical Brewing Co.",
    area: "Orlando",
    perk: "$1 off beers after the run",
    tags: ["all paces", "brewery", "verify"],
  },
];

export const races: Race[] = [
  {
    name: "AdventHealth July 4th Watermelon 5K",
    date: "2026-07-04",
    time: "7:30 AM",
    distance: "5K · 3.1 mi",
    price: "$35–50",
    location: "Park Ave, Winter Park",
    host: "Track Shack",
    blurb:
      "Central Florida’s biggest Independence Day run. Non-scored fun run, gender-specific tank, ice-cold watermelon and a watermelon-eating contest at the finish. Free Kids’ Run after.",
    note: "Packet pickup at Track Shack · Jun 30–Jul 3",
    registerUrl: "https://trackshack.com",
  },
  {
    name: "Celebration of Running — Lake Nona",
    date: "2026-09-19",
    time: "6:30 PM",
    distance: "5K",
    price: "TBD",
    location: "Lake Nona Town Center",
    host: "Track Shack",
    blurb: "Evening 5K through Lake Nona.",
    registerUrl: "https://trackshack.com",
  },
  {
    name: "DTO — Downtown Orlando 50th",
    date: "2026-12-05",
    time: "AM",
    distance: "Half + 5K",
    price: "early pricing",
    location: "Lake Eola Park",
    host: "Track Shack",
    blurb: "50-year milestone race weekend with a lakeside post-race party.",
    registerUrl: "https://trackshack.com",
  },
];

export const clubProfiles: Record<string, ClubProfile> = {
  "milk-district-run-club": {
    slug: "milk-district-run-club",
    bestFor:
      "social runners who want a relaxed weeknight 5K and a beer after — first-timers fit in easily, and nobody’s checking your watch.",
    realPace: "9–11 min/mi*",
    turnout: "40–60*",
    cards: [
      { icon: "users", label: "Typical turnout", answer: "40–60 on a normal Thursday; bigger when the weather’s good.", example: true },
      { icon: "gauge", label: "The real pace", answer: "They say “all paces” and mean it. Most run 9–11 min/mi; a small front group goes faster.", example: true },
      { icon: "split", label: "Pace groups?", answer: "Yes — the pack splits naturally. You will not be stuck alone at the back.", example: true },
      { icon: "age", label: "Crowd / age", answer: "Mostly late 20s–30s, mixed, friendly. Couples and solo runners both.", example: true },
      { icon: "cup", label: "Social after?", answer: "Big part of it — 15% off your tab at Sideward. Most people stay." },
      { icon: "park", label: "Parking", answer: "Street + nearby lots in the Milk District. Arrive ~15 min early on busy nights.", example: true },
      { icon: "wc", label: "Restrooms", answer: "Yes — inside Sideward Brewing before and after.", example: true },
      { icon: "dog", label: "Dogs / strollers?", answer: "Dog-friendly route; a few regulars bring pups. Strollers OK on the road loop.", example: true },
      { icon: "bulb", label: "Night lighting", answer: "Good on the main streets, dimmer on side roads. Bring something reflective in winter.", example: true },
      { icon: "bag", label: "Bag check?", answer: "No formal bag check — leave valuables in the car or keep it light.", example: true },
    ],
    fitGood: [
      "Want a low-pressure first group run",
      "Run anywhere from 9:00 to a walk/run",
      "Like hanging out (and a beer) afterward",
      "Prefer a big, easy-to-blend-into crowd",
    ],
    fitLess: [
      "Want a hard, structured tempo workout",
      "Need a fast front pack to push you (sub-7s)",
      "Prefer an early-morning run over a night one",
      "Want a small, quiet, no-frills group",
    ],
    scores: [
      { label: "First-timer friendly", value: 4, kind: "begin" },
      { label: "Social energy", value: 5, kind: "social" },
      { label: "Training intensity", value: 2, kind: "train" },
    ],
    ourTake: [
      "This is one of the easiest places in Orlando to show up alone and leave with people you know. The crowd skews late-20s to 30s, it’s genuinely no-pressure on pace, and the group naturally strings out so you’re never the obvious “last” person. The 15%-off tab at Sideward afterward is half the point — most people stick around.",
      "If you’re training for a goal race and need a hard session, this isn’t that night. Come for the community and the easy miles, not the splits.",
    ],
    steps: [
      { title: "Get there ~6:15", body: "Park in the Milk District; street parking and nearby lots fill up, so leave a buffer.", example: true },
      { title: "Find the group at Sideward", body: "Everyone gathers out front of Sideward Brewing. Just say “first time here” — someone will pull you in." },
      { title: "Run your pace", body: "The pack splits naturally into faster and slower groups. Walk-run is totally fine; there’s always someone in back." },
      { title: "Stick around after", body: "Most people grab a drink at Sideward (15% off). This is where you actually meet people — don’t skip it." },
    ],
    route: {
      summary: "~3.1 mi · flat · well-lit main roads",
      detail:
        "Surface: road · Elevation: flat · Lighting: good on main streets, dim on side roads",
    },
  },
};

export function getClub(slug: string): Club | undefined {
  return clubs.find((c) => c.slug === slug);
}

export function getProfile(slug: string): ClubProfile | undefined {
  return clubProfiles[slug];
}
